const easyQuestions = [
  { question: "What is 'cat' in Thai?", choices: ["แมว", "หมา", "นก", "ปลา"], correct: "แมว" },
  { question: "What do you drink in the morning?", choices: ["Water", "Coffee", "Juice", "All of these"], correct: "All of these" },
  { question: "Which is a vegetable?", choices: ["Apple", "Carrot", "Banana", "Orange"], correct: "Carrot" },
  { question: "What color are bananas?", choices: ["Red", "Yellow", "Blue", "Green"], correct: "Yellow" },
  { question: "Which one is a day of the week?", choices: ["January", "Monday", "Summer", "Night"], correct: "Monday" },
  { question: "What is the opposite of 'hot'?", choices: ["cold", "warm", "soft", "hard"], correct: "cold" },
  { question: "Which animal barks?", choices: ["Cat", "Dog", "Bird", "Fish"], correct: "Dog" },
  { question: "What is the plural of 'cat'?", choices: ["cats", "cat's", "cates", "catz"], correct: "cats" },
  { question: "Which one is a color?", choices: ["run", "blue", "quick", "jump"], correct: "blue" },
  { question: "How many legs does a spider have?", choices: ["6", "8", "4", "10"], correct: "8" },
  { question: "What sound does a dog make?", choices: ["meow", "quack", "woof", "moo"], correct: "woof" },
  { question: "Which is a fruit?", choices: ["carrot", "apple", "potato", "celery"], correct: "apple" },
  { question: "Choose the correct article: ___ apple", choices: ["A", "An", "The", "Some"], correct: "An" },
  { question: "What color is the sky on a clear day?", choices: ["Blue", "Green", "Red", "Black"], correct: "Blue" },
  { question: "How do you say 'สวัสดี' in English?", choices: ["Goodbye", "Thank you", "Hello", "Please"], correct: "Hello" },
  { question: "Which word is a verb?", choices: ["run", "blue", "table", "sweet"], correct: "run" },
  { question: "Which one is a fruit?", choices: ["Fish", "Orange", "Car", "Chair"], correct: "Orange" },
  { question: "What is 'water' in Thai?", choices: ["น้ำ", "ไฟ", "ลม", "ดิน"], correct: "น้ำ" },
  { question: "How many days are in a week?", choices: ["5", "6", "7", "8"], correct: "7" },
  { question: "Which is a farm animal?", choices: ["Lion", "Cow", "Shark", "Eagle"], correct: "Cow" },
  { question: "What do you wear on your feet?", choices: ["Hat", "Shoes", "Gloves", "Belt"], correct: "Shoes" },
  { question: "Which one is a body part?", choices: ["Table", "Chair", "Eye", "Phone"], correct: "Eye" },
  { question: "Which is used for writing?", choices: ["Pencil", "Plate", "Spoon", "Shoe"], correct: "Pencil" },
  { question: "What is 'red' in Thai?", choices: ["แดง", "เหลือง", "เขียว", "น้ำเงิน"], correct: "แดง" },
  { question: "Choose the correct greeting: 'Goodbye' means...", choices: ["สวัสดี", "ลาก่อน", "ขอบคุณ", "ขอโทษ"], correct: "ลาก่อน" },
  { question: "What is 2 + 2?", choices: ["3", "4", "5", "6"], correct: "4" },
  { question: "What color is grass?", choices: ["Green", "Blue", "Red", "Yellow"], correct: "Green" },
  { question: "What do you sleep on?", choices: ["Bed", "Table", "Shoe", "Car"], correct: "Bed" },
  { question: "Which animal says 'meow'?", choices: ["Dog", "Cat", "Cow", "Bird"], correct: "Cat" },
  { question: "Which season is usually cold?", choices: ["Summer", "Winter", "Autumn", "Spring"], correct: "Winter" }
];


const normalQuestions = [
  { question: "Complete the sentence: 'She ___ to school every day.'", choices: ["goes", "go", "going", "went"], correct: "goes" },
  { question: "What is the past tense of 'eat'?", choices: ["eated", "ate", "eats", "eating"], correct: "ate" },
  { question: "Which is a synonym for 'happy'?", choices: ["sad", "joyful", "angry", "tired"], correct: "joyful" },
  { question: "Which is an antonym for 'fast'?", choices: ["quick", "slow", "run", "jump"], correct: "slow" },
  { question: "Which is a question word?", choices: ["What", "Cat", "Run", "Blue"], correct: "What" },
  { question: "Which is a preposition?", choices: ["under", "run", "blue", "happy"], correct: "under" },
  { question: "What is the plural of 'child'?", choices: ["childs", "children", "childes", "child"], correct: "children" },
  { question: "Choose the correct past form of 'go'", choices: ["goes", "goed", "went", "gone"], correct: "went" },
  { question: "Which sentence is correct?", choices: ["He go to school", "He goes to school", "He going to school", "He go"], correct: "He goes to school" },
  { question: "What is the opposite of 'happy'?", choices: ["sad", "angry", "excited", "smile"], correct: "sad" },
  { question: "What is 12 divided by 4?", choices: ["3", "4", "2", "6"], correct: "3" },
  { question: "Which word is a noun?", choices: ["jump", "beautiful", "cat", "quickly"], correct: "cat" },
  { question: "How do you spell the number 40?", choices: ["fourty", "forty", "foury", "fouty"], correct: "forty" },
  { question: "What is the synonym of 'big'?", choices: ["small", "tiny", "large", "short"], correct: "large" },
  { question: "Which one is NOT an adjective?", choices: ["happy", "blue", "run", "tall"], correct: "run" },
  { question: "Which sentence is in present continuous?", choices: ["She eats", "She eating", "She is eating", "She eat"], correct: "She is eating" },
  { question: "Choose the correct article: '___ umbrella'", choices: ["A", "An", "The", "No article"], correct: "An" },
  { question: "Select the correct form: 'I have ___ English for two years.'", choices: ["learn", "learned", "been learning", "learning"], correct: "been learning" },
  { question: "Which is the correct comparative: 'My car is ___ than yours.'", choices: ["more fast", "faster", "fastest", "most fast"], correct: "faster" },
  { question: "Choose the correct preposition: 'She is good ___ math.'", choices: ["in", "at", "on", "for"], correct: "at" },
  { question: "Which is the correct past participle of 'go'?", choices: ["gone", "went", "goes", "going"], correct: "gone" },
  { question: "Choose the correct modal: 'You ___ finish your homework.'", choices: ["must", "may", "can", "would"], correct: "must" },
  { question: "Which sentence uses simple past?", choices: ["She eats dinner.", "She ate dinner.", "She is eating dinner.", "She has eaten dinner."], correct: "She ate dinner." },
  { question: "Choose the correct question tag: 'You're coming, ___?'", choices: ["aren't you", "isn't you", "won't you", "didn't you"], correct: "aren't you" },
  { question: "Which is the plural of 'mouse'?", choices: ["mouses", "mice", "mouse", "meese"], correct: "mice" },
  { question: "They ___ already left.", choices: ["have", "has", "had", "having"], correct: "have" },
  { question: "I am looking forward ___ your reply.", choices: ["to", "for", "on", "of"], correct: "to" },
  { question: "Which word is an adjective?", choices: ["beautiful", "run", "quickly", "happiness"], correct: "beautiful" },
  { question: "What is the plural of 'analysis'?", choices: ["analysises", "analyses", "analysises", "analysis"], correct: "analyses" },
  { question: "She is interested ___ music.", choices: ["in", "on", "at", "with"], correct: "in" }
];

const hardQuestions = [
  { question: "Choose the correct conditional: 'If I ___ rich, I would buy a house.'", choices: ["were", "was", "am", "be"], correct: "were" },
  { question: "What is the meaning of 'reluctant'?", choices: ["willing", "unwilling", "happy", "eager"], correct: "unwilling" },
  { question: "Which is a phrasal verb meaning 'search for information'?", choices: ["look up", "look after", "look in", "look out"], correct: "look up" },
  { question: "What is the past participle of 'write'?", choices: ["wrote", "written", "writing", "writtened"], correct: "written" },
  { question: "Which is an interjection?", choices: ["Wow!", "Run", "Blue", "Cat"], correct: "Wow!" },
  { question: "What is the superlative form of 'good'?", choices: ["goodest", "better", "best", "most good"], correct: "best" },
  { question: "Which is a synonym for 'rapid'?", choices: ["slow", "quick", "sad", "late"], correct: "quick" },
  { question: "Choose the correct: 'She ___ to the store yesterday.'", choices: ["go", "goed", "went", "gone"], correct: "went" },
  { question: "Which word is an antonym of 'expand'?", choices: ["shrink", "grow", "inflate", "extend"], correct: "shrink" },
  { question: "What does 'benevolent' mean?", choices: ["angry", "kind", "lazy", "selfish"], correct: "kind" },
  { question: "What is the correct form of 'run' in present perfect?", choices: ["ran", "runned", "run", "running"], correct: "run" },
  { question: "Which sentence is grammatically correct?", choices: ["He have never been to Japan.", "He has never been to Japan.", "He is never been to Japan.", "He had never been to Japan."], correct: "He has never been to Japan." },
  { question: "Choose the correct: 'If I ___ rich, I would travel the world.'", choices: ["was", "were", "am", "be"], correct: "were" },
  { question: "What is the passive form of 'They built a house'?", choices: ["A house built by them", "A house is built", "A house was built by them", "They were built a house"], correct: "A house was built by them" },
  { question: "Identify the adjective clause: 'The man who is wearing a hat is my uncle.'", choices: ["The man", "who is wearing a hat", "is my uncle", "wearing a hat"], correct: "who is wearing a hat" },
  { question: "What is the comparative form of 'good'?", choices: ["gooder", "more good", "better", "best"], correct: "better" },
  { question: "What is the meaning of 'to break the ice'?", choices: ["Destroy something", "Start a conversation", "Make something cold", "Avoid talking"], correct: "Start a conversation" },
  { question: "Choose the correct reported speech: He said, 'I will go home.'", choices: ["He said he will go home", "He said he would go home", "He said I will go home", "He said I would go home"], correct: "He said he would go home" },
  { question: "Which is a gerund?", choices: ["Running", "Run", "To run", "Ran"], correct: "Running" },
  { question: "Which word is an adverb?", choices: ["Quickly", "Quick", "Quicker", "Quickness"], correct: "Quickly" },
  { question: "Which sentence uses future perfect tense?", choices: ["She will eat", "She will be eating", "She will have eaten", "She is eating"], correct: "She will have eaten" },
  { question: "Choose the correct conditional: If I had known, I ___ gone.", choices: ["would have", "will have", "would", "had"], correct: "would have" },
  { question: "Which is an example of a metaphor?", choices: ["He is as fast as a cheetah", "He runs like a deer", "He is a shining star", "He is running fast"], correct: "He is a shining star" },
  { question: "Select the correct linking verb: 'She ___ tired after the trip.'", choices: ["is", "has", "does", "did"], correct: "is" },
  { question: "Choose the correct subjunctive: 'If he ___ here, he'd know.'", choices: ["were", "was", "is", "be"], correct: "were" },
  { question: "What does 'obfuscate' mean?", choices: ["to confuse", "to help", "to simplify", "to reveal"], correct: "to confuse" },
  { question: "Had she known, she ___ come.", choices: ["would have", "would", "will", "had"], correct: "would have" },
  { question: "Which is a countable noun?", choices: ["information", "advice", "fact", "knowledge"], correct: "fact" },
  { question: "What does the phrasal verb 'turn down' mean?", choices: ["accept", "reject", "increase", "lower"], correct: "reject" }
];

const lunaticQuestions = [
  { question: "What's the meaning of 'surreptitious'?", choices: ["kept secret", "very loud", "completely open", "well-known"], correct: "kept secret" },
  { question: "Complete: 'No sooner ___ I left than it started to rain.'", choices: ["had", "have", "has", "did"], correct: "had" },
  { question: "What's the meaning of 'ephemeral'?", choices: ["lasting very short time", "permanent", "very old", "traditional"], correct: "lasting very short time" },
  { question: "Which sentence contains a dangling participle?", choices: ["Walking down the street, the trees were beautiful.", "The trees were beautiful as I walked down the street.", "I walked down the street and saw beautiful trees.", "The street was beautiful."], correct: "Walking down the street, the trees were beautiful." },
  { question: "What is the meaning of 'defenestration'?", choices: ["Throwing out of a window", "Defending a nation", "A type of flower", "A kind of dance"], correct: "Throwing out of a window" },
  { question: "Which is an example of a zeugma?", choices: ["She broke his car and his heart.", "He ran quickly and quietly.", "The cat sat on the mat.", "They went to the store and bought apples."], correct: "She broke his car and his heart." },
  { question: "Which sentence uses an oxymoron?", choices: ["Bittersweet memories last forever.", "The cat is on the mat.", "He runs every morning.", "She likes apples."], correct: "Bittersweet memories last forever." },
  { question: "Which sentence uses a subjunctive mood?", choices: ["If I were you, I would go.", "I am going to the store.", "She likes ice cream.", "He will come tomorrow."], correct: "If I were you, I would go." },
  {  question: "What is the meaning of 'pulchritudinous'?", choices: ["Beautiful", "Ugly", "Dangerous", "Tiny"], correct: "Beautiful" },
  { question: "Which sentence contains an ellipsis?", choices: ["She went to the store, and I went to the store too.", "She went to the store, and I did too.", "She went to the store, and I also went.", "She went to the store, and I followed."], correct: "She went to the store, and I did too." },
  { question: "What does 'antediluvian' mean?", choices: ["Modern", "Ancient", "Flooded", "Unpredictable"], correct: "Ancient" },
  { question: "Identify the nominalization in the sentence: 'Her explanation was unclear.'", choices: ["Her", "Explanation", "Was", "Unclear"], correct: "Explanation" },
  { question: "Which sentence demonstrates syntactic ambiguity?", choices: ["Flying planes can be dangerous.", "Planes are dangerous when flying.", "Flying in planes is risky.", "Dangerous planes are flying."], correct: "Flying planes can be dangerous." },
  { question: "Choose the correct use of a reduced relative clause:", choices: ["The man who is sitting over there is my uncle.", "The man sitting over there is my uncle.", "The man he is sitting over there is my uncle.", "The man that sitting over there is my uncle."], correct: "The man sitting over there is my uncle." },
  { question: "What does 'sesquipedalian' describe?", choices: ["Short words", "Long words", "Simple speech", "Fast talking"], correct: "Long words" },
  { question: "Which sentence uses a correlative conjunction correctly?", choices: ["Either you come or stay.", "Neither the rain nor the wind could stop us.", "Both of them and she are going.", "Not only he but also her is late."], correct: "Neither the rain nor the wind could stop us." },
  { question: "What is the meaning of 'apocryphal'?", choices: ["Authentic", "Dubious", "Verified", "Transparent"], correct: "Dubious" },
  { question: "Which sentence uses a perfect infinitive correctly?", choices: ["She claims to have finished the work.", "She claims to finish the work.", "She claims finishing the work.", "She claims to be finishing the work."], correct: "She claims to have finished the work." },
  { question: "Choose the correct use of a conditional inversion:", choices: ["Had I known, I would have helped.", "If I had known, I would have helped.", "I would have helped if I had known.", "Knowing I had, I would have helped."], correct: "Had I known, I would have helped." },
  { question: "What does 'pellucid' mean?", choices: ["perfectly clear", "very dark", "complicated", "confusing"], correct: "perfectly clear" },
  { question: "Which word means 'present everywhere'?", choices: ["ubiquitous", "rare", "unique", "obscure"], correct: "ubiquitous" },
  { question: "Identify the correct subjunctive use: 'It is essential that he ___ present.'", choices: ["be", "is", "was", "being"], correct: "be" },
  { question: "What does 'perfidious' mean?", choices: ["deceitful", "perfect", "beneficial", "helpful"], correct: "deceitful" },
  { question: "Choose the correct archaic inversion: 'No sooner ___ he arrive than the phone rang.'", choices: ["had", "has", "did", "was"], correct: "had" },
  { question: "What does 'inchoate' mean?", choices: ["just begun", "finished", "perfected", "visible"], correct: "just begun" },
  { question: "Little ___ he know that trouble was coming.", choices: ["did", "does", "had", "has"], correct: "did" },
  { question: "What does 'lachrymose' mean?", choices: ["tearful", "happy", "angry", "sleepy"], correct: "tearful" },
  { question: "Which sentence is an example of antithesis?", choices: ["It was the best of times, it was the worst of times.", "She walked to the store.", "He ate quickly.", "They watched TV."], correct: "It was the best of times, it was the worst of times." },
  { question: "What does 'obstreperous' mean?", choices: ["noisy and difficult", "quiet and calm", "small and tiny", "fast and efficient"], correct: "noisy and difficult" }
];
